# Generated by Django 5.2.4 on 2025-12-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_visitlog_delete_sitevisit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Surat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Surat tavsifi')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Surat fayli')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Layklar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Saytda ko‘rsatilsinmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘yilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan sana')),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'Suratlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Video nomi')),
                ('description', models.TextField(blank=True, verbose_name='Video tavsifi')),
                ('video_url', models.URLField(verbose_name='Video havolasi (mp4 / YouTube / Drive)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', verbose_name='Video preview rasmi')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Video davomiyligi (masalan: 02:35)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar soni')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Layklar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Saytda ko‘rsatilsinmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘yilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan sana')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['-created_at'],
            },
        ),
    ]
