# Generated by Django 5.2.4 on 2025-12-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_photo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('photo', 'Rasm')], max_length=10, verbose_name='Turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/photos/', verbose_name='Rasm')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video havolasi (mp4 / YouTube / Drive)')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Video davomiyligi (faqat video uchun)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar soni (faqat video uchun)')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Layklar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘yilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Mediyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
