# Generated by Django 5.2.4 on 2025-12-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_media_delete_photo_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/', verbose_name='Video fayl'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video havolasi (YouTube / Drive)'),
        ),
    ]
