# Generated by Django 6.0 on 2026-01-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_media_video_file_alter_media_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Video davomiyligi (faqat video uchun)'),
        ),
    ]
