# Generated by Django 6.0 on 2026-01-31 10:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_media_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sovga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name="Sovg'a nomi")),
                ('tasvir', models.TextField(blank=True, verbose_name="Sovg'a tasviri")),
                ('foiz', models.IntegerField(help_text="1 dan 100 gacha bo'lgan foiz", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Yutuq foizi (%)')),
                ('katak_raqami', models.IntegerField(help_text='Barabanda joylashadigan katak raqami', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Katak raqami (1-10)')),
                ('rangi', models.CharField(default='#3498db', max_length=7, verbose_name='Katak rangi (HEX)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Sovg'a",
                'verbose_name_plural': "Sovg'alar",
            },
        ),
        migrations.CreateModel(
            name='BarabanSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_vaqti', models.DateTimeField(auto_now_add=True)),
                ('keyingi_spin_vaqti', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL)),
                ('sovga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sovga')),
            ],
            options={
                'verbose_name': 'Baraban aylantirish',
                'verbose_name_plural': 'Baraban aylantirishlar',
                'ordering': ['-spin_vaqti'],
            },
        ),
    ]
