# Generated by Django 6.0 on 2026-02-01 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sovga_barabanspin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barabanspin',
            options={'ordering': ['-spin_vaqti']},
        ),
        migrations.AlterModelOptions(
            name='sovga',
            options={'ordering': ['katak_raqami'], 'verbose_name': "Sovg'a", 'verbose_name_plural': "Sovg'alar"},
        ),
        migrations.AlterField(
            model_name='sovga',
            name='foiz',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Yutuq foizi (%)'),
        ),
        migrations.AlterField(
            model_name='sovga',
            name='katak_raqami',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Katak raqami'),
        ),
        migrations.AlterField(
            model_name='sovga',
            name='rangi',
            field=models.CharField(default='#3498db', max_length=7, verbose_name='Katak rangi'),
        ),
        migrations.CreateModel(
            name='Yutuq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_vaqti', models.DateTimeField(auto_now_add=True)),
                ('yutib_oldingi', models.BooleanField(default=True)),
                ('ishlatildi', models.BooleanField(default=False, verbose_name='Yutuq ishlatildimi?')),
                ('ishlatilgan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('izoh', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('sovga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yutuqlar', to='app.sovga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yutuqlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
                'ordering': ['-spin_vaqti'],
            },
        ),
    ]
