# Generated by Django 6.0 on 2026-02-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ad_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('text', 'Matn')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='ads/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
