# Generated by Django 6.0 on 2026-02-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='color',
            field=models.CharField(default='#ff6a00', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
